<?php

namespace Proxies\__CG__\keny\LeboncoinBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Annonce extends \keny\LeboncoinBundle\Entity\Annonce implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'date', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'priorite', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'cathegorie', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'region');
        }

        return array('__isInitialized__', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'date', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'priorite', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'cathegorie', '' . "\0" . 'keny\\LeboncoinBundle\\Entity\\Annonce' . "\0" . 'region');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Annonce $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriorite($priorite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriorite', array($priorite));

        return parent::setPriorite($priorite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriorite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriorite', array());

        return parent::getPriorite();
    }

    /**
     * {@inheritDoc}
     */
    public function addCathegorie(\keny\LeboncoinBundle\Entity\Cathegorie $cathegorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCathegorie', array($cathegorie));

        return parent::addCathegorie($cathegorie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCathegorie(\keny\LeboncoinBundle\Entity\Cathegorie $cathegorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCathegorie', array($cathegorie));

        return parent::removeCathegorie($cathegorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCathegorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCathegorie', array());

        return parent::getCathegorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion(\keny\LeboncoinBundle\Entity\Region $region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', array($region));

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', array());

        return parent::getRegion();
    }

}
