<?php

namespace keny\LeboncoinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CathegorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CathegorieRepository extends EntityRepository
{
}
